# Generated by Django 5.2.8 on 2025-12-01 10:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Author's name", max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='api_author_name_076641_idx')],
            },
        ),
        # Use raw SQL to drop the old integer author_id column and constraints
        migrations.RunSQL(
            sql=[
                "ALTER TABLE api_blogpost DROP CONSTRAINT IF EXISTS api_blogpost_author_id_fkey",
                "ALTER TABLE api_blogpost DROP COLUMN IF EXISTS author_id",
            ],
            reverse_sql=[
                # Reverse migration - recreate as integer (not perfect, but prevents errors)
                "ALTER TABLE api_blogpost ADD COLUMN author_id integer",
            ],
        ),
        # Add new author field (UUID FK to Author)
        migrations.AddField(
            model_name='blogpost',
            name='author',
            field=models.ForeignKey(
                help_text='Author of the blog post',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='blog_posts',
                to='api.author',
            ),
        ),
    ]
