# Generated by Django 5.2.8 on 2025-12-01 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_author_alter_blogpost_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='featured_image_url',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='featured_image',
            field=models.ImageField(blank=True, help_text='Featured image for the blog post', null=True, upload_to='blog_images/'),
        ),
    ]
