# Generated by Django 5.2.8 on 2025-12-01 11:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_blogpost_featured_image_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='read_time',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='views',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='tags',
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Tag name', max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='api_tag_name_38f172_idx'), models.Index(fields=['slug'], name='api_tag_slug_b1e5d4_idx')],
            },
        ),
        migrations.AddField(
            model_name='blogpost',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Tags for the blog post', related_name='blog_posts', to='api.tag'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Commenter's name", max_length=255)),
                ('email', models.EmailField(help_text="Commenter's email", max_length=254)),
                ('content', models.TextField(help_text='Comment content')),
                ('is_approved', models.BooleanField(default=False, help_text='Whether the comment is approved')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('blog_post', models.ForeignKey(help_text='Blog post this comment belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='api.blogpost')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['blog_post', 'created_at'], name='api_comment_blog_po_2c38ba_idx'), models.Index(fields=['is_approved'], name='api_comment_is_appr_5c52bd_idx')],
            },
        ),
    ]
